apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  lb_auth_issuer_uri: http://10.211.55.2:31823
  lb_usuarios_uri: http://10.211.55.2:30393
  port: "8001"
  db_host: mysql8:3306
  database: msvc_usuarios
  #username: root
  #password: Cduc1978.
  curso_url: msvc-cursos:8002
  msvc-usuarios.yml: |-
    config:
      texto: Configurando ambiente por defecto
    ---
    spring:
      config:
        activate:
          on-profile: dev
    config:
      texto: Configurando ambiente de desarrollo
    ---
    spring:
      config:
        activate:
          on-profile: prod
    config:
      texto: Configurando ambiente de produccion
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: postgres:5432
  database: msvc_cursos
  #username: postgres
  #password: Cduc1978.
  usuario_url: msvc-usuarios:8001