apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-catalogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-catalogs
  template:
    metadata:
      labels:
        app: api-catalogs
    spec:
      containers:
      - image: rodrigolopezkps/api-catalogs:latest
        name: api-catalogs
        ports:
        - containerPort: 8003
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: api-catalogs
                key: port
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: api-catalogs
                key: db_host
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: api-catalogs
                key: database
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: api-catalogs
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-catalogs
                key: password