apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      containers:
      - image: rodrigolopezkps/cursos:latest
        name: cursos
        ports:
        - containerPort: 8002
        env:
          - name: PORT
            #value: "8002"
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: port
          - name: DB_HOST
            #value: postgres:5432
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: db_host
          - name: DB_DATABASE
            #value: msvc_cursos
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: database
          - name: DB_USERNAME
            #value: postgres
            valueFrom:
              secretKeyRef:
                name: msvc-cursos
                key: username
          - name: DB_PASSWORD
            #value: Cduc1978.
            valueFrom:
              secretKeyRef:
                name: msvc-cursos
                key: password
          - name: USUARIOS_URL
            #value: msvc-usuarios:8001
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: usuario_url