apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres
  template:
    metadata:
      labels:
        role: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            #value: Cduc1978.
            valueFrom:
              secretKeyRef:
                name: msvc-cursos
                key: password
          - name: POSTGRES_DB
            #value: msvc_cursos
            valueFrom:
              configMapKeyRef:
                name: msvc-cursos
                key: database
        volumeMounts:
          - name: data-postgres
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: data-postgres
          #hostPath:
          #  path: /var/lib/postgresql/data
          #  type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: postgresql-pvc

