apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql8
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      containers:
      - image: mysql:8
        name: mysql
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            #value: Cduc1978.
            valueFrom:
              secretKeyRef:
                name: msvc-usuarios
                key: password
          - name: MYSQL_DATABASE
            #value: msvc_usuarios
            valueFrom:
              configMapKeyRef:
                name: msvc-usuarios
                key: database
        volumeMounts:
          - name: data-mysql
            mountPath: /var/lib/mysql
      volumes:
        - name: data-mysql
          #hostPath:
          #  path: /var/lib/mysql
          #  type: DirectoryOrCreate
          persistentVolumeClaim:
            claimName: mysql-pvc