version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Cduc1978.
      MYSQL_DATABASE: msvc_usuarios
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: Cduc1978.
      POSTGRES_DB: msvc_cursos
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    #image: usuarios
    image: rodrigolopezkps/usuarios:latest
    #build:
    #  context: ./
    #  dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    #env_file: ./msvc-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: root
      DB_PASSWORD: Cduc1978.
      CURSOS_URL: msvc-cursos:8002
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  msvc-cursos:
    container_name: msvc-cursos
    #image: cursos
    image: rodrigolopezkps/cursos:latest
    #build:
    #  context: .
    #  dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    #env_file: ./msvc-cursos/.env
    environment:
      PORT: 8002
      DB_HOST: postgres:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: Cduc1978.
      USUARIOS_URL: msvc-usuarios:8001
    networks:
      - spring
    depends_on:
      - postgres
      - msvc-usuarios
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres

networks:
  spring:
    name: spring
 #   external: true