apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  #For minikube: storageClassName: standard
  #For AWS:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
    #- ReadWriteMany
 # csi:
 #  driver: efs.csi.aws.com
 #   volumeHandle: fs-0c99434453833947c
  hostPath:
    path: /var/lib/mysql
    type: DirectoryOrCreate