apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  volumeName: mysql-pv
  accessModes:
   # - ReadWriteMany
   - ReadWriteOnce
  #storageClassName: standard
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi