apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  #storageClassName: standard
  storageClassName: ""
  accessModes:
    #- ReadWriteOnce
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-072f0e65f9d4b7b2e
  #hostPath:
  #  path: /var/lib/postgresql/data
  #  type: DirectoryOrCreate