apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  username: cm9vdA==
  password: Q2R1YzE5Nzgu
---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: Q2R1YzE5Nzgu
---
apiVersion: v1
kind: Secret
metadata:
  name: api-catalogs
type: Opaque
data:
  username: cm9vdA==
  password: Q2R1YzE5Nzgu