#FROM openjdk:21-oraclelinux8
#FROM eclipse-temurin
FROM eclipse-temurin:21.0.2_13-jdk
WORKDIR /app
COPY ./target/msvc-usuarios-0.0.1-SNAPSHOT.jar .
EXPOSE 8001
ENTRYPOINT ["java", "-jar", "msvc-usuarios-0.0.1-SNAPSHOT.jar"]
