package tech.kopernicus.data.specification.example.dataspecexample.model.dto;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.validation.annotation.Validated;

/**
 * Atributos de encabezado de la Oferta de Seguro
 */
@Schema(description = "Atributos de encabezado de la Oferta de Seguro")
@Validated
@jakarta.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-04-08T18:01:06.696186140Z[GMT]")


public class OfferOptionHeader   {
  @JsonProperty("optionId")
  private Integer optionId = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("totalPremium")
  private Float totalPremium = null;

  public OfferOptionHeader optionId(Integer optionId) {
    this.optionId = optionId;
    return this;
  }

  /**
   * Internal ID generated by the system.
   * @return optionId
   **/
  @Schema(example = "1", description = "Internal ID generated by the system.")
  
    public Integer getOptionId() {
    return optionId;
  }

  public void setOptionId(Integer optionId) {
    this.optionId = optionId;
  }

  public OfferOptionHeader currency(String currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Moneda.
   * @return currency
   **/
  @Schema(example = "USD", description = "Moneda.")
  
    public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public OfferOptionHeader name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Nombre de la opción.
   * @return name
   **/
  @Schema(example = "Plan A", description = "Nombre de la opción.")
  
    public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public OfferOptionHeader totalPremium(Float totalPremium) {
    this.totalPremium = totalPremium;
    return this;
  }

  /**
   * Get totalPremium
   * @return totalPremium
   **/
  @Schema(example = "200.5", description = "")
  
    public Float getTotalPremium() {
    return totalPremium;
  }

  public void setTotalPremium(Float totalPremium) {
    this.totalPremium = totalPremium;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OfferOptionHeader offerOptionHeader = (OfferOptionHeader) o;
    return Objects.equals(this.optionId, offerOptionHeader.optionId) &&
        Objects.equals(this.currency, offerOptionHeader.currency) &&
        Objects.equals(this.name, offerOptionHeader.name) &&
        Objects.equals(this.totalPremium, offerOptionHeader.totalPremium);
  }

  @Override
  public int hashCode() {
    return Objects.hash(optionId, currency, name, totalPremium);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OfferOptionHeader {\n");
    
    sb.append("    optionId: ").append(toIndentedString(optionId)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    totalPremium: ").append(toIndentedString(totalPremium)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
